#!/usr/bin/env node
// Offline transform: reads bagelbits/5e-database 2014 JSON and emits
// normalized JS modules to /js/data. Run via: node scripts/build-data.js
//
// NOTE: For Phase 1 MVP, /js/data/*.js files are hand-authored with SRD core content.
// This script exists as the documented pipeline for regenerating / expanding data
// once you've cloned `bagelbits/5e-database` into /vendor/5e-database.
//
// Usage:
//   cd vendor && git clone https://github.com/bagelbits/5e-database
//   node scripts/build-data.js
//
// The script below is a skeleton: it loads spells.json and emits
// /js/data/spells-full.js. Extend similar transforms for other categories.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "vendor", "5e-database", "src", "2014");
const OUT = path.join(ROOT, "js", "data");

async function readJson(file) {
  return JSON.parse(await fs.readFile(path.join(SRC, file), "utf8"));
}

function normalizeSpell(s) {
  return {
    id: s.index,
    name: s.name,
    level: s.level,
    school: (s.school?.index || s.school?.name || "").toLowerCase(),
    castingTime: s.casting_time,
    range: s.range,
    components: {
      v: (s.components || []).includes("V"),
      s: (s.components || []).includes("S"),
      m: (s.components || []).includes("M"),
      material: s.material || null
    },
    duration: s.duration,
    concentration: !!s.concentration,
    ritual: !!s.ritual,
    description: (s.desc || []).join("\n\n"),
    higherLevel: (s.higher_level || []).join("\n\n") || null,
    classes: (s.classes || []).map(c => c.index),
    source: "SRD 5.1"
  };
}

async function buildSpells() {
  try {
    const raw = await readJson("5e-SRD-Spells.json");
    const map = {};
    for (const s of raw) map[s.index] = normalizeSpell(s);
    const js =
`// Auto-generated by scripts/build-data.js. Do not edit by hand.
export const SPELLS = ${JSON.stringify(map, null, 2)};
export const SPELL_IDS = Object.keys(SPELLS);
`;
    await fs.writeFile(path.join(OUT, "spells-full.js"), js);
    console.log(`wrote spells-full.js (${Object.keys(map).length} spells)`);
  } catch (e) {
    console.error("spells:", e.message);
  }
}

// Add similar buildX() functions for races, classes, equipment, etc.
// See /js/data/*.js for the expected shapes.

buildSpells().catch(e => { console.error(e); process.exit(1); });
